name: Submit a benchmark
description: Submit a new benchmark to be included in the repo
title: "[benchmark]: <GPU>-<basecaller>-<version>-<model>"
labels: benchmark
assignees: Psy-Fer
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to run and submit a benchmark!
        ## Instructions
        Please update the title to include the benchmarked GPU, which basecaller was used, and with which model.
        For example, if you benchmarked an RTX 4090 with dorado version v0.9.1 using model dna_r10.4.1_e8.2_400bps_sup@v4.2.0, the title should be
        [benchmark]RTX 4090-dorado-v0.9.1-dna_r10.4.1_e8.2_400bps_sup@v4.2.0
        This will allow for quick triage of the benchmarking.
  - type: textarea
    id: time-data
    attributes:
      label: Runtime data
      description: Output data from command including /usr/bin/time -v output
      placeholder: Copy/paste output here
      value: ""
    validations:
      required: true
  - type: input
    id: samples-per-second
    attributes:
      label: Samples/s
      description: Samples per second as reported by the basecaller if available
      placeholder: 3.5e+e7
    validations:
      required: false
  - type: input
    id: basecaller
    attributes:
      label: Basecaller
      description: Which basecaller was used in the benchmark?
      placeholder: dorado
  - type: input
    id: version
    attributes:
      label: Basecaller version
      description: Which basecaller version was used in the benchmark?
      placeholder: v0.9.1
  - type: input
    id: model
    attributes:
      label: Basecaller model
      description: Which basecaller model was used in the benchmark?
      placeholder: dna_r10.4.1_e8.2_400bps_sup@v4.2.0
  - type: dropdown
    id: Dataset
    attributes:
      label: Benchmark dataset
      description: Which dataset was used for the benchmark?
      options:
      - PGXXXX230339_reads_chr22.pod5
      - PGXXXX230339_reads_chr22.blow5
      - Other
      default: 0
    validations:
      required: true
  - type: dropdown
    id: operating-system
    attributes:
      label: Operating System
      description: Which OS was the benchmark run on?
      options:
      - Linux
      - MacOS
      - Windows-WSL
      - Other
      default: 0
    validations:
      required: true
